exclude = "config.rmu"
homepage = "indexes/posts/docs-1.html"
longdate = "Jan 2, 2006"
# 26-Mar-2022: Github redirects to blog.methods.co.nz so do not need to change the urlprefix.
# urlprefix = "https://srackham.github.io/stuarts-notes"
urlprefix = "https://blog.methods.co.nz"
author = "Stuart Rackham"
templates = ".md"
id = "optional"

[user]
# Header text at the top of each page.
banner = "srackham | blog"

# Default HTML title element text.
title = "Stuart's Notes"

# Set shortname to your site's Disqus short name then uncomment the line to enable Disqus comments.
shortname = "stuarts-notes"

# Include highlight.js support.
highlightjs = "yes"