exclude = "config.rmu"
homepage = "indexes/posts/docs-1.html"
longdate = "Jan 2, 2006"
urlprefix = "http://blog.srackham.com"
author = "Stuart Rackham"
templates = ".md"

[user]
banner = "srackham | blog"